"""add preview_key to videos

Revision ID: 11f79a0f200b
Revises: cc4b240904e8
Create Date: 2026-03-31 18:16:58.350919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f79a0f200b'
down_revision: Union[str, Sequence[str], None] = 'cc4b240904e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('preview_key', sa.String(), nullable=True))
    op.drop_index(op.f('ix_videos_camera_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_videos_camera_id'), 'videos', ['camera_id'], unique=False)
    op.drop_column('videos', 'preview_key')
    # ### end Alembic commands ###
