"""add refresh tokens table

Revision ID: 4d5ecfa3c84d
Revises: 11f79a0f200b
Create Date: 2026-03-31 19:36:18.523725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5ecfa3c84d'
down_revision: Union[str, Sequence[str], None] = '11f79a0f200b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.String(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_column('refresh_tokens', 'revoked')
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###
