"""add refresh tokens

Revision ID: 8339d7c47a2b
Revises: 4d5ecfa3c84d
Create Date: 2026-03-31 19:36:49.810422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8339d7c47a2b'
down_revision: Union[str, Sequence[str], None] = '4d5ecfa3c84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
