"""init

Revision ID: cc4b240904e8
Revises: c19bb0881ce7
Create Date: 2026-03-29 15:22:54.934545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4b240904e8'
down_revision: Union[str, Sequence[str], None] = 'c19bb0881ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=False),
    sa.Column('camera_class_cd', sa.Integer(), nullable=True),
    sa.Column('camera_class', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('camera_place', sa.String(length=500), nullable=True),
    sa.Column('camera_place_cd', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('camera_type_cd', sa.Integer(), nullable=True),
    sa.Column('camera_type', sa.String(length=255), nullable=True),
    sa.Column('camera_latitude', sa.Float(), nullable=False),
    sa.Column('camera_longitude', sa.Float(), nullable=False),
    sa.Column('archive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('azimuth', sa.Integer(), nullable=True),
    sa.Column('process_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.create_index(op.f('ix_cameras_camera_name'), 'cameras', ['camera_name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('videos', sa.Column('camera_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_videos_camera_id'), 'videos', ['camera_id'], unique=False)
    op.drop_constraint(op.f('videos_user_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'videos', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_user_id_fkey'), 'videos', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_videos_camera_id'), table_name='videos')
    op.drop_column('videos', 'camera_id')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_cameras_camera_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
